version: "3.8"
services:
  webserver-api:
    image: nginx:1.19
    container_name: webserver-api
    ports:
      - 8888:80
    volumes:
      - ./api:/code
      # - ./frontend:/code/frontend
      - ./nginx/api.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build:
      context: .
    container_name: php
    env_file: ./.env
    volumes:
      - ./api:/code

  frontend:
    image: nginx:1.19
    container_name: webserver-front
    ports:
      - 5000:80
    volumes:
      - ./frontend:/code
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf
